---
- name: "Add a line in a file using module line in file"
  hosts: node01
  become: true
  tasks:
  - name: Add line "Welcome to KodeKloud" Labs! inside /var/www/html/index.html
    lineinfile:
      path: /var/www/html/index.html
      line: 'Welcome to KodeKloud Labs!'
      state: present
      insertbefore: BOF