apiVersion: v1
kind: Namespace
metadata:
  name: development

---
apiVersion: v1
kind: Pod
metadata:
  name: dev-app
  namespace: development
  labels:
    app: dev-app
spec:
  containers:
    - name: dev-app
      image: nginx:latest