apiVersion: v1
kind: Service
metadata:
  name: dev-app-service
  namespace: development
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
  selector:
      app: dev-app