apiVersion: v1
kind: Service
metadata:
  name: dev-app-service
  namespace: development
spec:
  type: NodePort
  selector:
    app: dev-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
