- name: Turn on instances by tag
  hosts: localhost
  become: true
  gather_facts: yes
  vars_files:
    - keys.yml
  tasks:
    - ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: stopped
        #wait: yes
        instance_tags:
          Name: Demo