- name: Create an AMI from an Image using the ec2_ami module
  hosts: localhost
  become: true
  vars_files:
    - keys.yml
  tasks:
    - name: Create new AMI
      ec2_snapshot_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
    - name: Create Volume Snapshot
      ec2_snapshot:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: i-exampleid
        device_name: /dev/xvdf
        state: present
        description: "On deman volume backup"