- name: Gather information from ec2 instances by state stopped
  hosts: localhost
  become: true
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          instance-state-name: stopped
      register: ec2_facts
    - debug:
        var: ec2_facts